# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu
menu:
- page: 首页
  url: /
  # icon: fa-home
- page: 前端
  url: /categories/前端/
  icon:
- page: 后端
  url: /categories/后端/
  icon:
- page: 工具
  url: /categories/工具/
  icon:
- page: 时间轴
  url: /archives/
  icon:

## favicon
favicon: /favicon.png

## Feed
rss: /atom.xml


# 各个小工具的设置

## widgets
widgets:
  - search
  - notification
  - social
  - category
  - archive
  - tagcloud
  - friends

## 搜索
jsonContent:
  searchLocal: true
  searchGoogle: false
  posts:
    title: true
    text: true
    content: true
    categories: true
    tags: true

## 网站公告设置
notification: |-
            <p>刚开的博客,谢谢关注^_^ <br/>

## 社交设置
social:
 - name: Github
   icon: git
   href: //github.com/sweida
 - name: 邮箱
   icon: envelope-o
   href: mailto:weidaxyy@163.com
#  - name: QQ群
#    icon: users
#    href: //jq.qq.com/?_wv=1027&k=5Cl8cXO
 - name: 联系QQ：849222104
   icon: qq
   href: javascript:;
 - name: 微博
   icon: weibo
   href: //weibo.com/207050005
 - name: RSS
   icon: feed
   href: /atom.xml

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   show_count: true
   order: -1

## 友链设置
links:
  - 博客园: http://www.cnblogs.com/shiweida/


# 主题自定义个性化配置

## 网站宣传语
branding: 人生若只如初见

## 设置banner背景图片
banner:
    img: http://7xpw2b.com1.z0.glb.clouddn.com/hexo-sinppet/img/banner.jpg

## 首页列表底部面板
homePanel: true

## 缩略图自定义随机图片
defaultImgs:
  -

## 截取文章首页描述字数
excerptLength: 120

## 代码高亮配置
highlightTheme: night bright

## bootstrap配置
bootstrap:

## ICON配置
fontAwesome:

## 文章过期提醒功能
warning:
  days: 300
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 文章内声明
declaration:
  enable: true
  title: '转载声明'
  tip: |-
      商业转载请联系作者获得授权,非商业转载请注明出处 © <a href="javascript:;">sweida</a>


## 主题评论

### gitment
gitment:
  enable: true
  owner: sweida
  repo: sweida.github.io
  client_id: 9a486808f778b7b4eac8
  client_secret: 78226662fa23e0991de5a220a2e2a233f43cae87
  perPage: 10

### 来必力
livere:
  enable: false
  livere_uid: MTAyMC8zMzA1MS85NjEz

### 友言评论(服务不稳定)
uyan:
  enable: false
  uyan_id: 1966422

### Disqus评论
disqus:
  enable: false
  shortname: snippet
  count: false

### 畅言评论(需要ICP备案)
changyan:
  enable: false
  appid: cytFm7yRx
  conf: 9386d5169653741bf612e45d3e932844

## 网站访问统计

### 网盟CNZZ统计
cnzz_analytics: 1263868967

### 百度统计
baidu_analytics:

### 谷歌统计
google_analytics:

### 腾讯分析
tencent_analytics:

### 百度文章推送
baidu_push:

#网站主题配置
since: 2018
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.2.1
