categories: 分类
search: 站内搜索
tags: 标签
tagcloud: 标签云
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts
newer: Newer
older: Older
share: Share
rss_feed: RSS
rss: RSS
category: Category
tag: Tag
social: 社交
friend_links: 友链
read_more: Read
home: Home
archives: 归档
about: About
search_local: 搜 索
search_google: googleSearch
author: Author
date: Published Date
update: Updated Date
post_categories: Categories
post_tags: Tags
post_licence: License
